<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-PennStateSoft-6ef7fbcb-e250-4a6e-82f5-b7478830631b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Components\Account\Pages\Manage\AdminLogin.razor" />
    <Content Remove="Components\Account\Pages\Manage\ComplaintPages\ComplaintReplyPages\EditComplaintForm.razor" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentEmail.Mailgun" Version="3.0.2" />
    <PackageReference Include="Microsoft.AspNet.Identity.Core" Version="2.2.4" />
    <PackageReference Include="Microsoft.AspNet.Identity.Owin" Version="2.2.4" />
    <PackageReference Include="Microsoft.AspNetCore.Components.QuickGrid.EntityFrameworkAdapter" Version="8.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.3" />
    <PackageReference Include="RestSharp" Version="111.4.0" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Components\Account\Pages\Manage\AdminLogin.razor" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="Components\Account\Pages\Manage\AdminLogin.razor" />
    <_ContentIncludedByDefault Remove="Components\Account\Pages\Manage\ComplaintPages\ComplaintReplyPages\EditComplaintForm.razor" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Migrations\ApplicationDb\" />
    <Folder Include="Migrations\Meeting\" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Components\Account\Pages\Manage\ComplaintPages\ComplaintReplyPages\EditComplaintForm.razor" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Components\Account\Pages\Manage\ComplaintPages\EditComplaintForm.razor" />
  </ItemGroup>

</Project>
